# Hal hal yang akan diajarkan

<blockquote> 1. Menjelaskan Pengenalan List dan Array </blockquote>
<blockquote> 2. Menjelaskan Tuple dan Dictionary  </blockquote>
<blockquote> 3. Menerapkan Operasi Aritmatika pada List/Array </blockquote>
<blockquote> 4. Menerpakan Perulangan pada List/Array </blockquote>
<blockquote> 5. Menerapkan Array Multidimensi </blockquote>

# Sifat Sifat Struktur Data

| Struktur Data   | Sifat-sifat                               | Mutable/Immutable       | Ordered/Unordered       | Duplicates Allowed |
|-----------------|-------------------------------------------|-------------------------|-------------------------|---------------------|
| List            | Koleksi elemen yang dapat diubah          | Mutable                 | Ordered                 | Duplicates Allowed  |
| Array (NumPy)   | Kumpulan elemen numerik multidimensi      | Mutable                 | Ordered (depends on axis)| Duplicates Allowed  |
| Dictionary      | Pasangan kunci-nilai yang tidak berurutan | Mutable                 | Unordered               | No Duplicate Keys   |
| Set             | Kumpulan elemen unik tanpa urutan         | Mutable (add/remove)    | Unordered               | No Duplicates       |
| Tuple           | Koleksi elemen yang tidak dapat diubah    | Immutable               | Ordered                 | Duplicates Allowed  |


- Mutable/Immutable: Mutable, artinya elemen-elemen di dalamnya bisa diubah setelah pembuatan list.
- Ordered/Unordered: Ordered, yang berarti list memiliki urutan tertentu. Elemen-elemennya dapat diakses berdasarkan indeks.
- Duplicates Allowed: Duplicates allowed, artinya list dapat berisi elemen yang sama lebih dari satu kali.

# Menjelaskan Pengenalan List dan Array

`Dalam Python`, perbedaan antara list dan array terletak pada karakteristik mereka. List memiliki fleksibilitas lebih besar dan dapat menyimpan berbagai jenis data. Sementara itu, array (modul array di Python) membutuhkan tipe data yang seragam untuk elemen-elemennya. Jika kecepatan atau penggunaan memori adalah perhatian utama, menggunakan array untuk tipe data yang seragam bisa lebih efisien.

## List

- List: Sebuah struktur data yang dapat menyimpan kumpulan elemen dengan berbagai jenis data. 
- Karakteristik: Mutable (dapat diubah), dapat diakses dengan indeks, dan dapat menampung berbagai jenis data.

In [24]:
Kosong = [] # List Kosong

In [25]:
IniList = [1, 2, 3, 'hello', 'world'] # List Bisa lebih dari satu tipe data

In [26]:
# Menggunakan Constructor, Dalam konteks pemrograman, sebuah constructor adalah metode khusus yang digunakan untuk membuat dan menginisialisasi objek dari sebuah kelas.

dataku = (1, 2, 3, 4, 5, 'a', 'b', 'c', 'd')
IniList2 = list(dataku)
print(IniList2)

[1, 2, 3, 4, 5, 'a', 'b', 'c', 'd']


In [27]:
# menggunakan looping
IniList3 = [i for i in range(0, 10)]
print(IniList3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
IniList4 = [i for i in "apakabar kalian semua"]
print(IniList4)

['a', 'p', 'a', 'k', 'a', 'b', 'a', 'r', ' ', 'k', 'a', 'l', 'i', 'a', 'n', ' ', 's', 'e', 'm', 'u', 'a']


In [31]:
IniList5 = [i for i in range(0, 10)]
# ditambahkan if

IniList6 = [i for i in IniList5 if i % 2 == 0]
print(IniList6)

[0, 2, 4, 6, 8]


In [32]:
# i dimanipulasi terlebih dahulu
IniList7 = [i**2 for i in range(0, 10) if i % 2 == 0]
print(IniList7)

[0, 4, 16, 36, 64]


## How to access

In [37]:
arrInt = [0, 1, 2, 3, 4, 5, 6, 7, 8, 10]

# print(arr[<start>:<stop>:<step>]) # akses list mulai dari <start> hingga <stop>, dengan loncatan <step>

print(arrInt[::]) # mengakses setiap elemen dalam list
print(arrInt[::2]) # mengakses mulai dari index 0 hingga akhir dengan lompatan 2 index
print(arrInt[1:5]) # mengakses setiap elemen dari index 1 hingga index 5
print(arrInt[2:9:3]) # mengakses mulai dari index 2 hingga index 9 dengan lompatan 3 index
print(arrInt[::-1]) # mengakses mulai dari index 0 hingga akhir dengan lompatan 1 index dari belakang
print(arrInt[-2::]) # mengakses mulai dari index 2 dari belakang hingga akhir

[0, 1, 2, 3, 4, 5, 6, 7, 8, 10]
[0, 2, 4, 6, 8]
[1, 2, 3, 4]
[2, 5, 8]
[10, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[8, 10]


## Beberapa function yang bisa digunakan untuk memanipulasi list

| Fungsi  | Penulisan                | Deskripsi                                        |
|:---------|:--------------------------|:--------------------------------------------------|
| append  | NamaList.append(nilai)   | Menambahkan data nilai pada list                  |
| len     | len(NamaList)            | Mencari panjang atau banyak data yang dimiliki list |
| sum     | sum(NamaList)            | Menghitung jumlah dari semua elemen dalam list    |
| min     | min(NamaList)            | Mengembalikan nilai terkecil dalam list           |
| max     | max(NamaList)            | Mengembalikan nilai terbesar dalam list           |
| insert  | NamaList.insert(index,nilai) | Menambahkan nilai di index yang dipilih       |
| remove  | NamaList.remove(nilai)   | Menghapus nilai tertentu di dalam list            |
| pop     | NamaList.pop()           | Mengapus data terakhir di list                    |
| extend  | NamaList.extend(listLain) | Menambahkan sebuah list ke dalam list             |
| clear   | NamaList.clear()         | Menghapus seluruh data di dalam list              |
| index   | NamaList.index(value)    | Mereturnkan index list dari value                 |
| count   | NamaList.count(value)    | Menghitung jumlah munculnya value yang dicari di dalam list |
| sort    | NamaList.sort()          | Mengurutkan nilai list secara ascending           |
| reverse | NamaList.reverse()       | Membalik urutan dari list                         |


## Array

- Array: Kumpulan elemen yang disusun dalam bentuk tabel dengan elemen-elemen yang memiliki indeks yang sama.
- Karakteristik: Struktur data serupa list tetapi dalam beberapa bahasa pemrograman, array membutuhkan elemen dengan tipe data yang seragam.

In [45]:
import array as arr

In [57]:
arr_arr = arr.array('i', [1, 2, 3, 4, 5])

In [58]:
arr_arr

array('i', [1, 2, 3, 4, 5])

In [50]:
import numpy as np

In [54]:
# Membuat numpy array dari list [1, 2, 3]
arr_np = np.array([1, "rend", 2, 3])

In [55]:
arr_np

array(['1', 'rend', '2', '3'], dtype='<U11')

In [59]:
listExample = [1, 2, 3, 4]
tupleExample = (5, 6, 7, 8)

arr1 = [-5, 13, 113, 56]
arr2 = [11, 56, 45, 39]
arr3 = [9, 81, 22, 93]
arrAll = [arr1, arr2, arr3]

arrayList = np.array(listExample)
arrayTuple = np.array(tupleExample)
array2D = np.array(arrAll)

In [60]:
arrayList

array([1, 2, 3, 4])

In [61]:
arrayTuple

array([5, 6, 7, 8])

In [62]:
array2D

array([[ -5,  13, 113,  56],
       [ 11,  56,  45,  39],
       [  9,  81,  22,  93]])

## How to access

In [114]:
# sama kayak list :)

# numpy.arange dan numpy.linspace

## np.arrange()

`np.arange` Method np.arange digunakan untuk mendeklarasikan dan menginisialisasi nilai array dengan nilai yang memiliki jarak yang sama dalam interval tertentu. Berikut adalah format penulisannya:

```python
arrArange = np.arange(<start>, <stop>, <step>, <dtype>)
```
-  start memiliki nilai default 0
-  stop wajib dituliskan
-  step memiliki nilai default 1
-  dtype memiliki nilai default int

In [65]:
arrArange1 = np.arange(10)
arrArange2 = np.arange(2, 9)
arrArange3 = np.arange(2, 12, 3)
arrArange4 = np.arange(1, 10, 2, float)

print('arrArange1:', arrArange1)
print('arrArange2:',arrArange2)
print('arrArange3:',arrArange3)
print('arrArange4:',arrArange4)

arrArange1: [0 1 2 3 4 5 6 7 8 9]
arrArange2: [2 3 4 5 6 7 8]
arrArange3: [ 2  5  8 11]
arrArange4: [1. 3. 5. 7. 9.]


## np.linspace()

`np.linspace` Method ini mirip dengan np.arange, namun perbedaannya ada di parameter step-nya. Apabila step pada np.arange dideklarasikan secara manual, maka step pada np.linspace dibuat secara otomatis berdasarkan 'banyak data yang diinginkan' dari start hingga stop. Semakin banyak data yang diinginkan, maka semakin kecil pula stepnya dan sebaliknya. Perhatikan format berikut:

```python
arrLins = np.linspace(<start>, <stop>, <num>, <retstep>, <dtype>)
```
-  start wajib dituliskan
-  stop wajib dituliskan
-  num memiliki nilai default 50
-  retstep memiliki nilai default False
-  dtype memiliki nilai default float

In [67]:
arrLins1 = np.linspace(2, 3)
arrLins2 = np.linspace(2, 3, 5)
arrLins3 = np.linspace(2, 3, 5, dtype=int)
arrLins4 = np.linspace(2, 3, 5, retstep=True)

print('arrLins1:', arrLins1) # akan ada sebanyak 50 data berjarak sama dari 2 sampai 3
print('arrLins2:', arrLins2) # Output: [2.   2.25 2.5  2.75 3.  ]
print('arrLins3:', arrLins3) # Output: [2 2 2 2 3]
print('arrLins4:', arrLins4) # Output: (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

arrLins1: [2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]
arrLins2: [2.   2.25 2.5  2.75 3.  ]
arrLins3: [2 2 2 2 3]
arrLins4: (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


## np.zeros() & numpy.ones()

In [147]:
arrZero1 = np.zeros(5)
arrZero2 = np.zeros(5, dtype=int)
arrZero3 = np.zeros((3, 4))
arrZero4 = np.zeros((2, 3, 4))


print(arrZero1, "\n", "---------")
print(arrZero2, "\n", "---------")
print(arrZero3, "\n", "---------")
print(arrZero4, "\n", "---------")


print("Jumlah dimensi array_2d:", arrZero3.ndim)
print("Jumlah dimensi array_3d:", arrZero4.ndim)

[0. 0. 0. 0. 0.] 
 ---------
[0 0 0 0 0] 
 ---------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 ---------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 
 ---------
Jumlah dimensi array_2d: 2
Jumlah dimensi array_3d: 3


# Operasi Aritmatika pada List/Array

In [70]:
# Mendefinisikan dua list
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]

In [74]:
list_1 + list_2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [77]:
# list_1 / list_2
# list_1 + list_2
# list_1 * list_2

In [71]:
# Penjumlahan list
hasil_penjumlahan = [a + b for a, b in zip(list_1, list_2)]
print("Penjumlahan list:", hasil_penjumlahan)  # Output: [7, 9, 11, 13, 15]

# Pengurangan list
hasil_pengurangan = [a - b for a, b in zip(list_1, list_2)]
print("Pengurangan list:", hasil_pengurangan)  # Output: [-5, -5, -5, -5, -5]

# Perkalian list (elemen-wise)
hasil_perkalian = [a * b for a, b in zip(list_1, list_2)]
print("Perkalian list:", hasil_perkalian)  # Output: [6, 14, 24, 36, 50]

# Pembagian list (elemen-wise)
hasil_pembagian = [a / b for a, b in zip(list_2, list_1)]
print("Pembagian list:", hasil_pembagian)  # Output: [6.0, 3.5, 2.6666666666666665, 2.25, 2.0]

Penjumlahan list: [7, 9, 11, 13, 15]
Pengurangan list: [-5, -5, -5, -5, -5]
Perkalian list: [6, 14, 24, 36, 50]
Pembagian list: [6.0, 3.5, 2.6666666666666665, 2.25, 2.0]


In [101]:
for hasil_zip in zip(list_1, list_2):
    print(hasil_zip)

(1, 6)
(2, 7)
(3, 8)
(4, 9)
(5, 10)


In [99]:
for a,b in zip(list_1, list_2):
    print(a, "+", b, "=", a + b)

1 + 6 = 7
2 + 7 = 9
3 + 8 = 11
4 + 9 = 13
5 + 10 = 15


In [ ]:
# list_1 = [1, 2, 3, 4, 5]
# list_2 = [6, 7, 8, 9, 10]

# # Penjumlahan list dengan loop
# hasil_penjumlahan = []
# for a, b in zip(list_1, list_2):
#     hasil_penjumlahan.append(a + b)
# print("Penjumlahan list:", hasil_penjumlahan)  # Output: [7, 9, 11, 13, 15]

# # Pengurangan list dengan loop
# hasil_pengurangan = []
# for a, b in zip(list_1, list_2):
#     hasil_pengurangan.append(a - b)
# print("Pengurangan list:", hasil_pengurangan)  # Output: [-5, -5, -5, -5, -5]

# # Perkalian list (elemen-wise) dengan loop
# hasil_perkalian = []
# for a, b in zip(list_1, list_2):
#     hasil_perkalian.append(a * b)
# print("Perkalian list:", hasil_perkalian)  # Output: [6, 14, 24, 36, 50]

# # Pembagian list (elemen-wise) dengan loop
# hasil_pembagian = []
# for a, b in zip(list_2, list_1):
#     hasil_pembagian.append(a / b)
# print("Pembagian list:", hasil_pembagian)  # Output: [6.0, 3.5, 2.6666666666666665, 2.25, 2.0]

# Dictionary

Membuat dictionary kosong

In [102]:
my_dict = {}

# Membuat dictionary dengan pasangan kunci-nilai
person = {
    'nama': 'John',
    'umur': 30,
    'pekerjaan': 'developer'
}

Mengakses nilai

In [103]:
# Mengakses nilai dengan kunci 'nama'
nama = person['nama']
print("Nama:", nama)  # Output: Nama: John

# Mengakses nilai dengan kunci 'umur'
umur = person['umur']
print("Umur:", umur)  # Output: Umur: 30

Nama: John
Umur: 30


Menambahkan pasangan

In [104]:
# Menambahkan pasangan kunci-nilai baru
person['kota'] = 'Jakarta'

# Memperbarui nilai untuk kunci yang sudah ada
person['umur'] = 31

print(person)
# Output: {'nama': 'John', 'umur': 31, 'pekerjaan': 'developer', 'kota': 'Jakarta'}

{'nama': 'John', 'umur': 31, 'pekerjaan': 'developer', 'kota': 'Jakarta'}


Menghapus pasangan

In [105]:
# Menghapus pasangan kunci-nilai 'umur'
del person['umur']

# Menghapus dan mendapatkan nilai yang dihapus dari kunci 'pekerjaan'
pekerjaan = person.pop('pekerjaan')

print(person)   # Output: {'nama': 'John', 'kota': 'Jakarta'}
print(pekerjaan)  # Output: developer


{'nama': 'John', 'kota': 'Jakarta'}
developer


# Latihan Soal

`Soal 1: Pengenalan List dan Array`

Buatlah program Python yang menerima dua list numerik dengan panjang yang sama. Program tersebut kemudian melakukan operasi penjumlahan, pengurangan, perkalian, dan pembagian pada setiap elemen dari kedua list tersebut. Tampilkan hasil operasi aritmatika tersebut.

`Soal 2: Tuple, Dictionary, dan Perulangan`

Buatlah sebuah program Python yang meminta pengguna untuk memasukkan data (nama dan usia) sejumlah lima orang, dan simpan data tersebut ke dalam sebuah dictionary. Setelah itu, gunakan perulangan untuk menampilkan setiap pasangan nama dan usia dari dictionary tersebut.

`Soal 3: Array Multidimensi`

Buatlah sebuah program Python menggunakan NumPy atau array biasa dalam Python untuk membuat sebuah array dua dimensi berisi angka acak. Program tersebut kemudian mencari nilai maksimum dari setiap baris dan nilai minimum dari setiap kolom dalam array tersebut. Tampilkan nilai maksimum dari setiap baris dan nilai minimum dari setiap kolom.