In [1]:
# Memasukkan dua list numerik dengan panjang yang sama
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]

# Operasi aritmatika pada setiap elemen dari kedua list
hasil_penjumlahan = [a + b for a, b in zip(list_1, list_2)]
hasil_pengurangan = [a - b for a, b in zip(list_1, list_2)]
hasil_perkalian = [a * b for a, b in zip(list_1, list_2)]
hasil_pembagian = [a / b for a, b in zip(list_1, list_2)]

# Menampilkan hasil operasi aritmatika
print("Hasil Penjumlahan:", hasil_penjumlahan)
print("Hasil Pengurangan:", hasil_pengurangan)
print("Hasil Perkalian:", hasil_perkalian)
print("Hasil Pembagian:", hasil_pembagian)


Hasil Penjumlahan: [7, 9, 11, 13, 15]
Hasil Pengurangan: [-5, -5, -5, -5, -5]
Hasil Perkalian: [6, 14, 24, 36, 50]
Hasil Pembagian: [0.16666666666666666, 0.2857142857142857, 0.375, 0.4444444444444444, 0.5]


In [8]:
# Meminta pengguna memasukkan data dan menyimpannya dalam dictionary
data = {}
for i in range(2):
    nama = input("Masukkan nama: ")
    usia = int(input("Masukkan usia: "))
    data[nama] = usia

# Menampilkan pasangan nama dan usia menggunakan perulangan pada dictionary
print("")

print("Data yang dimasukkan:")

for nama, usia in data.items():
    print(f"Nama: {nama}, Usia: {usia} tahun")


Masukkan nama: Rendika
Masukkan usia: 20
Masukkan nama: Sayyid'
Masukkan usia: 50

Data yang dimasukkan:
Nama: Rendika, Usia: 20 tahun
Nama: Sayyid', Usia: 50 tahun


In [3]:
import numpy as np

# Membuat array dua dimensi berisi angka acak
array_2d = np.random.randint(1, 100, size=(5, 5))

# Mencari nilai maksimum dari setiap baris dan nilai minimum dari setiap kolom
max_per_baris = np.max(array_2d, axis=1)
min_per_kolom = np.min(array_2d, axis=0)

# Menampilkan nilai maksimum dari setiap baris dan nilai minimum dari setiap kolom
print("Nilai Maksimum dari Setiap Baris:")
print(max_per_baris)
print("\nNilai Minimum dari Setiap Kolom:")
print(min_per_kolom)

Nilai Maksimum dari Setiap Baris:
[91 97 72 67 72]

Nilai Minimum dari Setiap Kolom:
[60 10 13 28 19]


In [9]:
array_2d

array([[91, 58, 30, 57, 19],
       [97, 10, 57, 80, 96],
       [72, 39, 52, 28, 49],
       [60, 34, 67, 54, 20],
       [66, 72, 13, 33, 48]])